name: Output Test
on: [workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: test
        env:
          BUILD_BRANCH_NAME: ${{ github.ref_name }}
        run: echo "${{ env.BUILD_BRANCH_NAME }}"
      - id: step1
        run: echo "::set-output name=test::${{ steps.env.BUILD_BRANCH_NAME }}"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
